# Using Pandas

In [209]:
#Still working on it. To finish th
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 200)
## to make it possible to display multiple output inside one cell 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<b>load the data from the vehicles.csv file into pandas data frame

In [193]:
## Your Code here
df=pd.read_csv("data/vehicles.csv")
df=pd.DataFrame(df)
print(df.head())

               Make                Model  Year  Engine Displacement  \
0        AM General    DJ Po Vehicle 2WD  1984                  2.5
1        AM General     FJ8c Post Office  1984                  4.2
2        AM General  Post Office DJ5 2WD  1985                  2.5
3        AM General  Post Office DJ8 2WD  1985                  4.2
4  ASC Incorporated                  GNX  1987                  3.8

   Cylinders     Transmission        Drivetrain                Vehicle Class  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars

  Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0   Regular          19.388824        18           17            17
1   Regular          25.354615        13           13            13
2   Regular          20.600625        16           17            16
3   Regular          25.354615        13           13            13
4   Premium          20.600625        14           21            16

   CO2 Emission Grams/Mile  Fuel Cost/Year
0               522.764706            1950
1               683.615385            2550
2               555.437500            2100
3               683.615385            2550
4               555.437500            2550

In [194]:
cars_df = df
cars_df.head()

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

In [138]:
cars_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

First exploration of the dataset:

- How many observations does it have?
- Look at all the columns: do you understand what they mean?
- Look at the raw data: do you see anything weird?
- Look at the data types: are they the expected ones for the information the column contains?

In [208]:
## Your Code here
#How many observations does it have?
print(cars_df.tail)#35952

<bound method NDFrame.tail of                    Make                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5
1            AM General     FJ8c Post Office  1984                  4.2
2            AM General  Post Office DJ5 2WD  1985                  2.5
3            AM General  Post Office DJ8 2WD  1985                  4.2
4      ASC Incorporated                  GNX  1987                  3.8
...                 ...                  ...   ...                  ...
35947             smart         fortwo coupe  2013                  1.0
35948             smart         fortwo coupe  2014                  1.0
35949             smart         fortwo coupe  2015                  1.0
35950             smart         fortwo coupe  2016                  0.9
35951             smart         fortwo coupe  2016                  0.9

       Cylinders     Transmission        Drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive
1            6.0  Automatic 3-spd     2-Wheel Drive
2            4.0  Automatic 3-spd  Rear-Wheel Drive
3            6.0  Automatic 3-spd  Rear-Wheel Drive
4            6.0  Automatic 4-spd  Rear-Wheel Drive
...          ...              ...               ...
35947        3.0        Auto(AM5)  Rear-Wheel Drive
35948        3.0        Auto(AM5)  Rear-Wheel Drive
35949        3.0        Auto(AM5)  Rear-Wheel Drive
35950        3.0        Auto(AM6)  Rear-Wheel Drive
35951        3.0     Manual 5-spd  Rear-Wheel Drive

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18
1      Special Purpose Vehicle 2WD   Regular          25.354615        13
2      Special Purpose Vehicle 2WD   Regular          20.600625        16
3      Special Purpose Vehicle 2WD   Regular          25.354615        13
4                     Midsize Cars   Premium          20.600625        14
...                            ...       ...                ...       ...
35947                  Two Seaters   Premium           9.155833        34
35948                  Two Seaters   Premium           9.155833        34
35949                  Two Seaters   Premium           9.155833        34
35950                  Two Seaters   Premium           9.155833        34
35951                  Two Seaters   Premium           9.417429        32

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year
0               17            17               522.764706            1950
1               13            13               683.615385            2550
2               17            16               555.437500            2100
3               13            13               683.615385            2550
4               21            16               555.437500            2550
...            ...           ...                      ...             ...
35947           38            36               244.000000            1100
35948           38            36               243.000000            1100
35949           38            36               244.000000            1100
35950           39            36               246.000000            1100
35951           39            35               255.000000            1150

[35952 rows x 15 columns]>

In [139]:
#Look at all the columns: do you understand what they mean?
print("yes"+", there are 15 headers describing features of diffrent cars ")
display(cars_df.head())

yes, there are 15 headers describing features of diffrent cars

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

### Cleaning and wrangling data

- Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton". If you find similar examples, clean their names too. Use `loc` with boolean indexing.

- Convert CO2 Emissions from Grams/Mile to Grams/Km

- Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use `pandas.Series.str.startswith` and .

- convert MPG columns to km_per_liter

Note:
<br>Converting Grams/Mile to Grams/Km

1 Mile = 1.60934 Km

Converting Gallons to Liters

1 Gallon = 3.78541 Liters

In [165]:
#Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton". If you find similar examples, clean their names too. Use loc with boolean indexing.

Dutton =cars_df.loc[cars_df['Make'].str.contains('Dutton')]
Dutton

cars_df.loc[cars_df['Make'].str.contains('Dutton'),"Make"] = 'Dutton'
Dutton2 =cars_df.loc[cars_df['Make'].str.contains('Dutton')]
Dutton2

#cars_df=df
#df
#cars_df['Make']
#cars_df
print(cars_df['Make'].str.contains('Dutton'))

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
11012,"E. P. Dutton, Inc.",Funeral Coach,1985,4.1,8.0,Automatic 4-spd,Front-Wheel Drive,Special Purpose Vehicles,Regular,19.388824,15,21,17,522.764706,1950
30164,S and S Coach Company E.p. Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,9,11,10,888.700000,3350
31754,Superior Coaches Div E.p. Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,10,11,10,888.700000,3350

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
11012,Dutton,Funeral Coach,1985,4.1,8.0,Automatic 4-spd,Front-Wheel Drive,Special Purpose Vehicles,Regular,19.388824,15,21,17,522.764706,1950
30164,Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,9,11,10,888.700000,3350
31754,Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,10,11,10,888.700000,3350

0        False
1        False
2        False
3        False
4        False
         ...
35947    False
35948    False
35949    False
35950    False
35951    False
Name: Make, Length: 35952, dtype: bool

In [172]:
#Convert CO2 Emissions from Grams/Mile to Grams/Km
#1 Mile = 1.60934 Km
cars_df['CO2 Emission Grams/Km'] = cars_df['CO2 Emission Grams/Mile']/1.6093
cars_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,CO2 Emission Grams/Km
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,324.839810
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.790520
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,345.142298
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.790520
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,345.142298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.618716
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,150.997328
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.618716
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,152.861493
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,158.453986

In [190]:
#Create a binary column that solely indicates if the transmission of a car is automatic or manual. 
#Use pandas.Series.str.startswith
cars_df['Auto_Transmission'] = cars_df['Transmission'].str.startswith('Auto')
cars_df['Manual_Transmission'] = cars_df['Transmission'].str.startswith("Manual")
cars_df
#help ("pandas.Series.str.startswith")

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG_km_per_liter,Highway MPG_km_per_liter,Combined MPG_km_per_liter,CO2 Emission Grams/Mile,Fuel Cost/Year,Auto_Transmission,Manual_Transmission
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,True,False
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,True,False
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,True,False
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,True,False
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,True,False
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,True,False
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,True,False
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,True,False
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,False,True

In [183]:
#convert MPG columns to km_per_liter
cars_df.rename(columns={'City MPG':'City MPG_km_per_liter'}, inplace=True)
cars_df.rename(columns={'Highway MPG':'Highway MPG_km_per_liter'}, inplace=True)
cars_df.rename(columns={'Combined MPG':'Combined MPG_km_per_liter'}, inplace=True)
cars_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG_km_per_liter,Highway MPG_km_per_liter,Combined MPG_km_per_liter,CO2 Emission Grams/Mile,Fuel Cost/Year,Auto_Transmission,Manual_Transmission
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,True,False
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,True,False
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,True,False
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,True,False
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,True,False
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,True,False
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,True,False
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,True,False
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,False,True

#Look at the raw data: do you see anything weird?
print("yes." + " Slash, spaces in the headers need to be replaced with underscore. \n They may affect readability and analysis when calling for the header names. \n Also, the names of the cars are missing.")
display(cars_df.head())

In [52]:
## Your Code here
#Look at the data types: are they the expected ones for the information the column contains?
#print(type(cars_df))
print("yes " + "the data type is: ")
print(type(cars_df["Fuel Barrels/Year"]))
#<class 'pandas.core.series.Series'>

yes the data type is:
<class 'pandas.core.series.Series'>

### Gathering insights:

- How many car makers are there? How many models? Which car maker has the most cars in the dataset?

- When were these cars made? How big is the engine of these cars?

- What's the frequency of different transmissions, drivetrains and fuel types?

- What's the car that consumes the least/most fuel?

In [96]:
# Your Code here
#How many car makers are there? How many models? Which car maker has the most cars in the dataset?
makers = cars_df["Make"].nunique()
model = cars_df["Model"].nunique()
print("There are", makers, "makers", "and", model, "models.")
#print(cars_df["Make"].count()-1)
display(cars_df.head())#35952

There are 127 makers and 3608 models.

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

In [114]:
#most_car_maker = cars_df["Make"].mode()
#print(most_car_maker)

Largest = cars_df["Make"].value_counts().nlargest(10)

most_car_maker = cars_df["Make"].value_counts().idxmax()
print(most_car_maker, "has the most cars in the dataset with", Largest[0], "models")
print(Largest)

Chevrolet has the most cars in the dataset with 3643 models
Chevrolet        3643
Ford             2946
Dodge            2360
GMC              2347
Toyota           1836
BMW              1677
Mercedes-Benz    1284
Nissan           1253
Volkswagen       1047
Mitsubishi        950
Name: Make, dtype: int64

<b> (Optional)

What brand has the worse CO2 Emissions on average?

Hint: use the function `sort_values()`

In [231]:
## your Code here
check1=cars_df.sort_values(by=["CO2 Emission Grams/Mile"],ascending=False)
#check1
check2=cars_df. loc[cars_df["CO2 Emission Grams/Mile"].idxmax()]
#check2 
check3=cars_df["CO2 Emission Grams/Mile"].max()
#check3
check4=cars_df.loc[cars_df["CO2 Emission Grams/Mile"] > 1269]
check4
check5=cars_df[cars_df["CO2 Emission Grams/Mile"] >1269]
check5

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
20894,Lamborghini,Countach,1986,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800
20895,Lamborghini,Countach,1987,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800
20896,Lamborghini,Countach,1988,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800
20897,Lamborghini,Countach,1989,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
20894,Lamborghini,Countach,1986,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800
20895,Lamborghini,Countach,1987,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800
20896,Lamborghini,Countach,1988,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800
20897,Lamborghini,Countach,1989,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800

Do cars with automatic transmission consume more fuel than cars with manual transmission on average?

In [264]:
## Your Code is here 
print("Yes.", "Cars with Automatic transmission has a higher average CO2 Emission Grams/Mile of 487.39 n\ compared to 450.16 of cars with manual transmission")
check1=cars_df.sort_values(by=["CO2 Emission Grams/Mile"],ascending=False)
#check1
Auto=check1[check1['Transmission'].str.contains('Auto')| check1['Transmission'].str.contains('auto')]
Auto
Manual=check1[check1['Transmission'].str.contains('Manual')|check1['Transmission'].str.contains('manual')]
Manual

mean_Auto = Auto["CO2 Emission Grams/Mile"].mean()
mean_Manual = Manual["CO2 Emission Grams/Mile"].mean()

print("Automatic Transmission mean:", mean_Auto, "CO2 Emission Grams/Mile") #487.39345033639324
print("Manual Transmission mean:", mean_Manual, "CO2 Emission Grams/Mile")#450.1617321474516

Yes. Cars with Automatic transmission has a higher average CO2 Emission Grams/Mile of 487.39 n\ compared to 450.16 of cars with manual transmission

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
34125,Vector,W8,1993,6.0,8.0,Automatic 3-spd,Rear-Wheel Drive,Two Seaters,Premium,41.201250,7,10,8,1110.875,5050
30086,Rolls-Royce,Silver Spur Limousine,1985,6.8,8.0,Automatic 3-spd,Rear-Wheel Drive,Large Cars,Regular,41.201250,7,9,8,1110.875,4150
34124,Vector,W8,1992,6.0,8.0,Automatic 3-spd,Rear-Wheel Drive,Two Seaters,Premium,41.201250,7,10,8,1110.875,5050
29979,Rolls-Royce,Corniche II,1987,6.8,8.0,Automatic 3-spd,Rear-Wheel Drive,Subcompact Cars,Regular,41.201250,7,9,8,1110.875,4150
426,Aston Martin,Lagonda,1985,5.3,8.0,Automatic 3-spd,Rear-Wheel Drive,Subcompact Cars,Regular,41.201250,7,9,8,1110.875,4150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7917,Chevrolet,Volt,2017,1.5,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,Regular Gas or Electricity,2.006844,43,42,42,51.000,800
7916,Chevrolet,Volt,2016,1.5,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,Regular Gas or Electricity,2.006844,43,42,42,51.000,800
3070,BMW,i3 REX,2015,0.6,2.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,41,37,39,40.000,1050
3069,BMW,i3 REX,2014,0.6,2.0,Auto(A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,41,37,39,40.000,1050
3071,BMW,i3 REX,2016,0.6,2.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,41,37,39,37.000,1050

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
20897,Lamborghini,Countach,1989,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800
20896,Lamborghini,Countach,1988,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800
20895,Lamborghini,Countach,1987,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800
20894,Lamborghini,Countach,1986,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,1269.571429,5800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17530,Honda,Insight,2004,1.0,3.0,Manual 5-spd,Front-Wheel Drive,Two Seaters,Regular,6.338654,48,58,52,170.903846,650
17526,Honda,Insight,2002,1.0,3.0,Manual 5-spd,Front-Wheel Drive,Two Seaters,Regular,6.219057,48,59,53,167.679245,650
17528,Honda,Insight,2003,1.0,3.0,Manual 5-spd,Front-Wheel Drive,Two Seaters,Regular,6.219057,48,59,53,167.679245,650
17522,Honda,Insight,2000,1.0,3.0,Manual 5-spd,Front-Wheel Drive,Two Seaters,Regular,6.219057,49,61,53,167.679245,650
17524,Honda,Insight,2001,1.0,3.0,Manual 5-spd,Front-Wheel Drive,Two Seaters,Regular,6.219057,48,60,53,167.679245,650

Automatic Transmission mean: 487.39345033639324 CO2 Emission Grams/Mile
Manual Transmission mean: 450.1617321474516 CO2 Emission Grams/Mile